name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  easy_locale: ^0.0.3
  easychat:
    path: ..
  easyuser:
    path: ../../easyuser
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  easychat:
    path: ..
  easyuser:
    path: ../../easyuser

flutter:
  uses-material-design: true
