name: easychat
description: "Full featured and complete chat package for Flutter and Firebase"
version: 0.1.1
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.11
  easy_realtime_database: ^0.0.7
  easy_report: ^0.0.5
  easy_storage: ^0.0.13
  easy_url_preview: ^0.0.4
  easyuser: ^0.0.26
  firebase_auth: 5.1.1
  firebase_core: 3.1.1
  firebase_database: 11.0.2
  firebase_ui_database: ^1.4.4
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easychat
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - chat
  - chat-ui
  - firebase
  - realtime-database
  - easy-packages
