name: easy_messaging
description: "Provides an easy way of handling Firebase Cloud Messaging service"
version: 0.0.4
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  device_info_plus: ^10.1.1
  easy_helpers: ^0.0.11
  easy_realtime_database: ^0.0.3
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  firebase_messaging: ^15.0.2
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_like
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - fcm
  - push-notifications
  - messaging
  - easy-packages
